#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE9CBDFC0ABC0A854 (scdbackup@gmx.net)
#
Name     : libisofs
Version  : 1.4.8
Release  : 1
URL      : http://files.libburnia-project.org/releases/libisofs-1.4.8.tar.gz
Source0  : http://files.libburnia-project.org/releases/libisofs-1.4.8.tar.gz
Source99 : http://files.libburnia-project.org/releases/libisofs-1.4.8.tar.gz.sig
Summary  : ISO9660 filesystem creation library
Group    : Development/Tools
License  : GPL-2.0
Requires: libisofs-lib
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : pkgconfig(zlib)

%description
------------------------------------------------------------------------------
libisofs
------------------------------------------------------------------------------

%package dev
Summary: dev components for the libisofs package.
Group: Development
Requires: libisofs-lib
Provides: libisofs-devel

%description dev
dev components for the libisofs package.


%package lib
Summary: lib components for the libisofs package.
Group: Libraries

%description lib
lib components for the libisofs package.


%prep
%setup -q -n libisofs-1.4.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515693032
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1515693032
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libisofs/libisofs.h
/usr/lib64/libisofs.so
/usr/lib64/pkgconfig/libisofs-1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libisofs.so.6
/usr/lib64/libisofs.so.6.84.0
