#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0xE9CBDFC0ABC0A854 (scdbackup@gmx.net)
#
Name     : libisofs
Version  : 1.5.4
Release  : 8
URL      : http://files.libburnia-project.org/releases/libisofs-1.5.4.tar.gz
Source0  : http://files.libburnia-project.org/releases/libisofs-1.5.4.tar.gz
Source1  : http://files.libburnia-project.org/releases/libisofs-1.5.4.tar.gz.asc
Summary  : ISO9660 filesystem creation library
Group    : Development/Tools
License  : GPL-2.0
Requires: libisofs-lib = %{version}-%{release}
Requires: libisofs-license = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
------------------------------------------------------------------------------
libisofs
------------------------------------------------------------------------------

%package dev
Summary: dev components for the libisofs package.
Group: Development
Requires: libisofs-lib = %{version}-%{release}
Provides: libisofs-devel = %{version}-%{release}
Requires: libisofs = %{version}-%{release}

%description dev
dev components for the libisofs package.


%package lib
Summary: lib components for the libisofs package.
Group: Libraries
Requires: libisofs-license = %{version}-%{release}

%description lib
lib components for the libisofs package.


%package license
Summary: license components for the libisofs package.
Group: Default

%description license
license components for the libisofs package.


%prep
%setup -q -n libisofs-1.5.4
cd %{_builddir}/libisofs-1.5.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702015666
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1702015666
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libisofs
cp %{_builddir}/libisofs-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libisofs/5405311284eab5ab51113f87c9bfac435c695bb9 || :
cp %{_builddir}/libisofs-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/libisofs/2236b80df839204a4250cd722f9f2178c77b387a || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libisofs/libisofs.h
/usr/lib64/libisofs.so
/usr/lib64/pkgconfig/libisofs-1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libisofs.so.6
/usr/lib64/libisofs.so.6.91.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libisofs/2236b80df839204a4250cd722f9f2178c77b387a
/usr/share/package-licenses/libisofs/5405311284eab5ab51113f87c9bfac435c695bb9
